# ********RoostGPT********

# Test generated by RoostGPT for test apispec-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /listener/communicationMessage_post for http method type POST 
# RoostTestHash=fdd5ae6c84
# 
# 

# ********RoostGPT********
Feature: Communication Message Listener

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Test POST /listener/communicationMessage with valid payloads
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "<city>",
              "cityCode": <cityCode>,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [<subscriberId1>]
                  },
                  "olt": "<olt1>",
                  "station": "<station1>"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [<subscriberId2>]
                  },
                  "olt": "<olt2>",
                  "station": "<station2>"
                }
              ],
              "location": "<location>",
              "locationAbbreviation": "<locationAbbreviation>",
              "locationCode": <locationCode>,
              "stateAbbreviation": "<stateAbbreviation>"
            },
            {
              "city": "<city2>",
              "cityCode": <cityCode2>,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [<subscriberId3>]
                  },
                  "olt": "<olt3>",
                  "station": "<station3>"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [<subscriberId4>]
                  },
                  "olt": "<olt4>",
                  "station": "<station4>"
                }
              ],
              "location": "<location2>",
              "locationAbbreviation": "<locationAbbreviation2>",
              "locationCode": <locationCode2>,
              "stateAbbreviation": "<stateAbbreviation2>"
            }
          ],
          "type": "<serviceType>"
        },
        "company": "<company>",
        "emissionDate": "<emissionDate>",
        "eventType": "<eventType>",
        "id": "<id>",
        "identifiedFailure": "<identifiedFailure>",
        "messageType": "<messageType>",
        "promiseDate": "<promiseDate>",
        "startDate": "<startDate>",
        "status": "<status>",
        "ticketNumber": "<ticketNumber>",
        "type": "<type>"
      }
      """
    When method POST
    Then status <expectedStatus>
    And match response == '#? _ == null || typeof _ == "object"'
    And match response.affectedService == '#? _ == null || typeof _ == "object"'
    And match response.affectedService.address == '#? _ == null || typeof _ == "array"'
    And match each response.affectedService.address[*].city == '##string'
    And match each response.affectedService.address[*].cityCode == '##number'
    And match each response.affectedService.address[*].equipment == '#? _ == null || typeof _ == "array"'
    And match each response.affectedService.address[*].equipment[*].affectedCustomers == '#? _ == null || typeof _ == "object"'
    And match each response.affectedService.address[*].equipment[*].affectedCustomers.subscriberId == '#? _ == null || typeof _ == "array"'
    And match each response.affectedService.address[*].equipment[*].affectedCustomers.subscriberId[*].subscriberId == '##number'
    And match each response.affectedService.address[*].equipment[*].olt == '##string'
    And match each response.affectedService.address[*].equipment[*].station == '##string'
    And match each response.affectedService.address[*].location == '##string'
    And match each response.affectedService.address[*].locationAbbreviation == '##string'
    And match each response.affectedService.address[*].locationCode == '##number'
    And match each response.affectedService.address[*].stateAbbreviation == '##string'
    And match response.affectedService.type == '##string'
    And match response.company == '##string'
    And match response.emissionDate == '##string'
    And match response.eventType == '##string'
    And match response.id == '##string'
    And match response.identifiedFailure == '##string'
    And match response.messageType == '##string'
    And match response.promiseDate == '##string'
    And match response.startDate == '##string'
    And match response.status == '##string'
    And match response.ticketNumber == '##string'
    And match response.type == '##string'

    Examples:
      | city       | cityCode | subscriberId1 | olt1            | station1 | subscriberId2 | olt2            | station2 | location   | locationAbbreviation | locationCode | stateAbbreviation | city2    | cityCode2 | subscriberId3 | olt3            | station3 | subscriberId4 | olt4            | station4 | location2 | locationAbbreviation2 | locationCode2 | stateAbbreviation2 | serviceType   | company   | emissionDate          | eventType                    | id          | identifiedFailure    | messageType  | promiseDate           | startDate             | status         | ticketNumber  | type         | expectedStatus |
      | 'SAO LUIS' |  2111300 | ['8022201']   | 'MA-CTO04-GHUA' | 'CTO'    | ['8022202']   | 'MA-ITZ02-GHUA' | 'ITZ'    | 'SAO LUIS' | 'SLS'                |        98000 | 'MA'              | 'BELEM'  |   1501402 | ['8022203']   | 'PA-CTO10-GHUA' | 'CTO'    | ['8022201']   | 'PA-CTO10-GHUA' | 'ICY'    | 'BELEM'   | 'BLM'                 |         91000 | 'PA'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Lentidão'                   | '210067783' | 'Rompimento de cabo' | 'Comunicado' | '2022-06-30T16:20:40' | '2022-06-29T12:05:00' | 'Abertura'     | '43246567'    | 'Incidente'  |            204 |
      | 'SAO LUIS' |  2111300 | ['8022201']   | 'MA-CTO04-GHUA' | 'CTO'    | ['8022202']   | 'MA-ITZ02-GHUA' | 'ITZ'    | 'SAO LUIS' | 'SLS'                |        98000 | 'MA'              | 'BELEM'  |   1501402 | ['8022203']   | 'PA-CTO10-GHUA' | 'CTO'    | ['8022201']   | 'PA-CTO10-GHUA' | 'ICY'    | 'BELEM'   | 'BLM'                 |         91000 | 'PA'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Interrupção não programada' | '194753'    | ''                   | 'Comunicado' | '2022-06-30T16:20:40' | '2022-06-29T12:05:00' | 'Abertura'     | '2023_019473' | 'Incidente'  |            204 |
      | 'MANAUS'   |  2111300 | ['8022201']   | 'AM-PA01-GALC'  | 'PA'     | ['8022202']   | 'AM-PA01-GALC'  | 'PA'     | 'MANAUS'   | 'MNS'                |        92000 | 'AM'              | 'OLINDA' |   2609600 | ['8022203']   | 'PE-ECCA3-GALC' | 'ECCA'   | ['8022201']   | 'PE-ECCA4-GALC' | 'ECCA'   | 'OLINDA'  | 'OLD'                 |         81103 | 'PE'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | ''                           | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Abertura'     | ''            | 'Manutenção' |            204 |
      | 'SAO LUIS' |  2111300 | ['8022201']   | 'MA-CTO04-GHUA' | 'CTO'    | ['8022202']   | 'MA-ITZ02-GHUA' | 'ITZ'    | 'SAO LUIS' | 'SLS'                |        98000 | 'MA'              | 'BELEM'  |   1501402 | ['8022203']   | 'PA-CTO10-GHUA' | 'CTO'    | ['8022201']   | 'PA-CTO10-GHUA' | 'ICY'    | 'BELEM'   | 'BLM'                 |         91000 | 'PA'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Lentidão'                   | '210067783' | 'Rompimento de cabo' | 'Comunicado' | '2022-06-30T16:20:40' | '2022-06-29T12:05:00' | 'Atualização'  | '43246567'    | 'Incidente'  |            204 |
      | 'SAO LUIS' |  2111300 | ['8022201']   | 'MA-CTO04-GHUA' | 'CTO'    | ['8022202']   | 'MA-ITZ02-GHUA' | 'ITZ'    | 'SAO LUIS' | 'SLS'                |        98000 | 'MA'              | 'BELEM'  |   1501402 | ['8022203']   | 'PA-CTO10-GHUA' | 'CTO'    | ['8022201']   | 'PA-CTO10-GHUA' | 'ICY'    | 'BELEM'   | 'BLM'                 |         91000 | 'PA'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Interrupção não programada' | '210067783' | ''                   | 'Comunicado' | '2022-06-30T16:20:40' | '2022-06-29T12:05:00' | 'Atualização'  | '43246567'    | 'Incidente'  |            204 |
      | 'MANAUS'   |  2111300 | ['8022201']   | 'AM-PA01-GALC'  | 'PA'     | ['8022202']   | 'AM-PA01-GALC'  | 'PA'     | 'MANAUS'   | 'MNS'                |        92000 | 'AM'              | 'OLINDA' |   2609600 | ['8022203']   | 'PE-ECCA3-GALC' | 'ECCA'   | ['8022201']   | 'PE-ECCA4-GALC' | 'ECCA'   | 'OLINDA'  | 'OLD'                 |         81103 | 'PE'               | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | ''                           | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Atualização'  | ''            | 'Manutenção' |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Lentidão'                   | '210067783' | 'Rompimento de cabo' | 'Comunicado' | ''                    | ''                    | 'Cancelamento' | ''            | 'Incidente'  |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | 'Banda Larga' | 'CP_XPTO' | '2022-06-28T12:16:00' | 'Interrupção não programada' | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Cancelamento' | ''            | 'Incidente'  |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | ''            | 'CP_XPTO' | ''                    | ''                           | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Cancelamento' | ''            | 'Manutenção' |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | 'Banda Larga' | 'CP_XPTO' | ''                    | ''                           | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Atualização'  | ''            | 'Manutenção' |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | 'Banda Larga' | 'CP_XPTO' | ''                    | 'Interrupção não programada' | '210067783' | ''                   | 'Comunicado' | ''                    | ''                    | 'Finalização'  | ''            | 'Incidente'  |            204 |
      | ''         | ''       | []            | ''              | ''       | []            | ''              | ''       | ''         | ''                   | ''           | ''                | ''       | ''        | []            | ''              | ''       | []            | ''              | ''       | ''        | ''                    | ''            | ''                 | 'Banda Larga' | 'CP_XPTO' | ''                    | 'Lentidão'                   | '210067783' | 'Rompimento de cabo' | 'Comunicado' | ''                    | ''                    | 'Finalização'  | ''            | 'Incidente'  |            204 |

  Scenario: Test POST /listener/communicationMessage with missing required fields
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "SAO LUIS",
              "cityCode": 2111300,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-CTO04-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-ITZ02-GHUA",
                  "station": "ITZ"
                }
              ],
              "location": "SAO LUIS",
              "locationAbbreviation": "SLS",
              "locationCode": 98000,
              "stateAbbreviation": "MA"
            },
            {
              "city": "BELEM",
              "cityCode": 1501402,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022203,
                      8022201,
                      8022202
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "ICY"
                }
              ],
              "location": "BELEM",
              "locationAbbreviation": "BLM",
              "locationCode": 91000,
              "stateAbbreviation": "PA"
            }
          ],
          "type": "Banda Larga"
        },
        "company": "CP_XPTO",
        "emissionDate": "2022-06-28T12:16:00",
        "eventType": "Lentidão",
        "id": "210067783",
        "identifiedFailure": "Rompimento de cabo",
        "messageType": "Comunicado",
        "promiseDate": "2022-06-30T16:20:40",
        "startDate": "2022-06-29T12:05:00",
        "status": "Abertura",
        "ticketNumber": "43246567",
        "type": "Incidente"
      }
      """
    When method POST
    Then status 400
    And match response.error.code == '##number'
    And match response.error.message == '##string'

  Scenario: Test POST /listener/communicationMessage with invalid data types
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": 12345,
              "cityCode": "invalid",
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      "invalid",
                      "invalid",
                      "invalid"
                    ]
                  },
                  "olt": 12345,
                  "station": 12345
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      "invalid",
                      "invalid",
                      "invalid"
                    ]
                  },
                  "olt": 12345,
                  "station": 12345
                }
              ],
              "location": 12345,
              "locationAbbreviation": 12345,
              "locationCode": "invalid",
              "stateAbbreviation": 12345
            },
            {
              "city": 12345,
              "cityCode": "invalid",
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      "invalid",
                      "invalid",
                      "invalid"
                    ]
                  },
                  "olt": 12345,
                  "station": 12345
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      "invalid",
                      "invalid",
                      "invalid"
                    ]
                  },
                  "olt": 12345,
                  "station": 12345
                }
              ],
              "location": 12345,
              "locationAbbreviation": 12345,
              "locationCode": "invalid",
              "stateAbbreviation": 12345
            }
          ],
          "type": 12345
        },
        "company": 12345,
        "emissionDate": 12345,
        "eventType": 12345,
        "id": 12345,
        "identifiedFailure": 12345,
        "messageType": 12345,
        "promiseDate": 12345,
        "startDate": 12345,
        "status": 12345,
        "ticketNumber": 12345,
        "type": 12345
      }
      """
    When method POST
    Then status 400
    And match response.error.code == '##number'
    And match response.error.message == '##string'

  Scenario: Test POST /listener/communicationMessage with unauthorized access
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "SAO LUIS",
              "cityCode": 2111300,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-CTO04-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-ITZ02-GHUA",
                  "station": "ITZ"
                }
              ],
              "location": "SAO LUIS",
              "locationAbbreviation": "SLS",
              "locationCode": 98000,
              "stateAbbreviation": "MA"
            },
            {
              "city": "BELEM",
              "cityCode": 1501402,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022203,
                      8022201,
                      8022202
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "ICY"
                }
              ],
              "location": "BELEM",
              "locationAbbreviation": "BLM",
              "locationCode": 91000,
              "stateAbbreviation": "PA"
            }
          ],
          "type": "Banda Larga"
        },
        "company": "CP_XPTO",
        "emissionDate": "2022-06-28T12:16:00",
        "eventType": "Lentidão",
        "id": "210067783",
        "identifiedFailure": "Rompimento de cabo",
        "messageType": "Comunicado",
        "promiseDate": "2022-06-30T16:20:40",
        "startDate": "2022-06-29T12:05:00",
        "status": "Abertura",
        "ticketNumber": "43246567",
        "type": "Incidente"
      }
      """
    When method POST
    Then status 401
    And match response.error.code == '##number'
    And match response.error.message == '##string'

  Scenario: Test POST /listener/communicationMessage with server error
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "SAO LUIS",
              "cityCode": 2111300,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-CTO04-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-ITZ02-GHUA",
                  "station": "ITZ"
                }
              ],
              "location": "SAO LUIS",
              "locationAbbreviation": "SLS",
              "locationCode": 98000,
              "stateAbbreviation": "MA"
            },
            {
              "city": "BELEM",
              "cityCode": 1501402,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022203,
                      8022201,
                      8022202
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "ICY"
                }
              ],
              "location": "BELEM",
              "locationAbbreviation": "BLM",
              "locationCode": 91000,
              "stateAbbreviation": "PA"
            }
          ],
          "type": "Banda Larga"
        },
        "company": "CP_XPTO",
        "emissionDate": "2022-06-28T12:16:00",
        "eventType": "Lentidão",
        "id": "210067783",
        "identifiedFailure": "Rompimento de cabo",
        "messageType": "Comunicado",
        "promiseDate": "2022-06-30T16:20:40",
        "startDate": "2022-06-29T12:05:00",
        "status": "Abertura",
        "ticketNumber": "43246567",
        "type": "Incidente"
      }
      """
    When method POST
    Then status 500
    And match response.error.code == '##number'
    And match response.error.message == '##string'

  Scenario: Test POST /listener/communicationMessage with service unavailable
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "SAO LUIS",
              "cityCode": 2111300,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-CTO04-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-ITZ02-GHUA",
                  "station": "ITZ"
                }
              ],
              "location": "SAO LUIS",
              "locationAbbreviation": "SLS",
              "locationCode": 98000,
              "stateAbbreviation": "MA"
            },
            {
              "city": "BELEM",
              "cityCode": 1501402,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022203,
                      8022201,
                      8022202
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "ICY"
                }
              ],
              "location": "BELEM",
              "locationAbbreviation": "BLM",
              "locationCode": 91000,
              "stateAbbreviation": "PA"
            }
          ],
          "type": "Banda Larga"
        },
        "company": "CP_XPTO",
        "emissionDate": "2022-06-28T12:16:00",
        "eventType": "Lentidão",
        "id": "210067783",
        "identifiedFailure": "Rompimento de cabo",
        "messageType": "Comunicado",
        "promiseDate": "2022-06-30T16:20:40",
        "startDate": "2022-06-29T12:05:00",
        "status": "Abertura",
        "ticketNumber": "43246567",
        "type": "Incidente"
      }
      """
    When method POST
    Then status 503
    And match response.error.code == '##number'
    And match response.error.message == '##string'

  Scenario: Test POST /listener/communicationMessage with timeout
    Given path '/listener/communicationMessage'
    And request
      """
      {
        "affectedService": {
          "address": [
            {
              "city": "SAO LUIS",
              "cityCode": 2111300,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-CTO04-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "MA-ITZ02-GHUA",
                  "station": "ITZ"
                }
              ],
              "location": "SAO LUIS",
              "locationAbbreviation": "SLS",
              "locationCode": 98000,
              "stateAbbreviation": "MA"
            },
            {
              "city": "BELEM",
              "cityCode": 1501402,
              "equipment": [
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022203,
                      8022201,
                      8022202
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "CTO"
                },
                {
                  "affectedCustomers": {
                    "subscriberId": [
                      8022201,
                      8022202,
                      8022203
                    ]
                  },
                  "olt": "PA-CTO10-GHUA",
                  "station": "ICY"
                }
              ],
              "location": "BELEM",
              "locationAbbreviation": "BLM",
              "locationCode": 91000,
              "stateAbbreviation": "PA"
            }
          ],
          "type": "Banda Larga"
        },
        "company": "CP_XPTO",
        "emissionDate": "2022-06-28T12:16:00",
        "eventType": "Lentidão",
        "id": "210067783",
        "identifiedFailure": "Rompimento de cabo",
        "messageType": "Comunicado",
        "promiseDate": "2022-06-30T16:20:40",
        "startDate": "2022-06-29T12:05:00",
        "status": "Abertura",
        "ticketNumber": "43246567",
        "type": "Incidente"
      }
      """
    When method POST
    Then status 504
    And match response.error.code == '##number'
    And match response.error.message == '##string'
