# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=b16b61c2ee
# 
# 

# ********RoostGPT********
Feature: Testing the /country API Endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers =
      """
      {
        "Authorization": karate.properties['AUTH_TOKEN'],
        "app-identifier": "d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d",
        "customer-secret-key": "12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe"
      }
      """

  Scenario Outline: Test POST /country API with valid payload and validate the response
    Given path '/country'
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    When method POST
    Then status 201
    And match response.status == 'success'
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#[] string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_post.csv') |

  Scenario: Test POST /country API with missing required fields
    Given path '/country'
    And request
      """
      {
        "code": "IND",
        "currencies": ["INR", "USD", "EURO"],
        "default_currency": "INR",
        "is_active": 1
      }
      """
    When method POST
    Then status 400
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

  Scenario Outline: Test invalid data types in POST /country
    Given path '/country'
    And request
      """
      {
        "name": <name>,
        "code": <code>,
        "currencies": <currencies>,
        "default_currency": <default_currency>,
        "is_active": <is_active>
      }
      """
    When method POST
    Then status 400
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | name         | code      | currencies       | default_currency | is_active |
      |        12345 | 'Invalid' | ['INR', 'USD']   | 'INR'            |         1 |
      | 'Valid Name' |       123 | ['USD']          | 'USD'            | 'TRUE'    |
      | 'Another'    | null      | ['Not an array'] | null             |         1 |
