# ********RoostGPT********

# Test generated by RoostGPT for test karate-iteration-check_clone using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=963f6fa808
# 
# 

# ********RoostGPT********
Feature: Country API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Delete Country by ID
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method delete
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '##string'

    Examples:
      | read('country_id_delete.csv') |
