# ********RoostGPT********

# Test generated by RoostGPT for test karate-iteration-check_clone using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=7383d796c0
# 
# 

# ********RoostGPT********
Feature: Update Country by ID

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update country with valid data
    Given path 'country', <id>
    And request
      """
      { 
        "name": <name>, 
        "code": <code>, 
        "currencies": <currencies>, 
        "default_currency": <default_currency>, 
        "is_active": <is_active> 
      }
      """
    And header app-identifier = <app_identifier>
    And header customer-secret-key = <customer_secret_key>
    When method put
    Then status 200
    And match response.status == 'success'
    And match response.message == '##string'
    And match response.data.id == <id>
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '##string'
    And match response.data.default_currency == '##string'
    And match response.data.is_active == '##number'
    And match response.data.app_id == '##number'
    And match response.data.customer_id == '##number'
    And match response.data.created_by == '##number'
    And match response.data.updated_by == '##number'
    And match response.data.created_at == '##string'
    And match response.data.updated_at == '##string'
    And match each response.data.currencies[*] == '##string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_put.csv') |
