# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=e5eb5af926
# 
# 

# ********RoostGPT********
Feature: Update Country by ID API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: karate.properties['bearerAuth'] }

  Scenario Outline: Validate Update Country by ID Endpoint with valid input
    Given path '/country/<id>'
    And param id = <id>
    And request { name: '<name>', code: '<code>', currencies: <currencies>, default_currency: '<default_currency>', is_active: <is_active> }
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method PUT
    Then status <status_code>
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#date'
    And match response.data.updated_at == '#date'
    And match response.data.currencies == '#array'
    And match each response.data.currencies[*] == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id | name    | code  | currencies             | default_currency | is_active | app_identifier                                                 | customer_secret_key                                            | status_code |
      | 32 | 'INDIA' | 'IND' | ['INR', 'USD', 'EURO'] | 'INR'            |         1 | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d' | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' |         200 |
