# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=3d9e7cb5d1
# 
# 

# ********RoostGPT********
Feature: Tests for /country API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: GET /country - Validate response for valid headers and successful operation
    Given path 'country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Data fetched successfully'
    And match response.data.countries == '#[]'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#? _ == null || typeof _ == "string"'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#[]'
    And match each response.data.countries[*].currencies == '#array'

    Examples:
      | read('country_get.csv') |

  Scenario Outline: GET /country - Validate response for valid headers and error case (Invalid Keys)
    Given path 'country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method GET
    Then status != 200
    And match response == '##object'

    Examples:
      | app_identifier                                                 | customer_secret_key                                            |
      | 'invalid_app_identifier'                                       | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' |
      | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d' | 'invalid_customer_secret_key'                                  |
