# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete Country by ID

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Validate delete country API for success response
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method DELETE
    Then status 200
    And match response.status == '##string'
    And match response.message == '##string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_delete.csv') |
