# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Test /country/{id} API endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Testing /country/{id} with valid ID, app-identifier and customer-secret-key
    Given path '/country/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method GET
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data == '#object'
    And match response.data.country.id == '#number'
    And match response.data.country.name == '#? _ == null || typeof _ == "string"'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#[]'
    And match each response.data.country.currencies[*] == '#string'

    Examples:
      | read('country_id_get.csv') |

  Scenario Outline: Testing /country/{id} with invalid inputs
    Given path '/country/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method GET
    Then status 400
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id | app_identifier                                                 | customer_secret_key                                            |
      | -1 | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d' | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' |
      |  0 | 'invalid-app-identifier'                                       | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' |
