# ********RoostGPT********

# Test generated by RoostGPT for test karate-iteration-check_clone using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=0c14e24fdf
# 
# 

# ********RoostGPT********
Feature: Country API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Get country by ID
    Given path 'country', <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method get
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data == '#object'
    And match response.data.country.id == '#number'
    And match response.data.country.name == '##string'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#[]'
    And match response.error_info == '##string'

    Examples:
      | read('country_id_get.csv') |
