# ********RoostGPT********

# Test generated by RoostGPT for test karate-iteration-check_clone using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=dc1526474c
# 
# 

# ********RoostGPT********
Feature: Country API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Validate GET /country endpoint with valid headers
    Given path '/country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method get
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data == '#object'
    And match response.data.countries == '#array'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '##string'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#array'
    And match response.error_info == '##string'

    Examples:
      | read('country_get.csv') |
