# ********RoostGPT********

# Test generated by RoostGPT for test karate-iteration-check_clone using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=c24da7c390
# 
# 

# ********RoostGPT********
Feature: Country API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a new country
    Given path '/country'
    And request
      """
      { 
        "name": "<name>", 
        "code": "<code>", 
        "currencies": <currencies>, 
        "default_currency": "<default_currency>", 
        "is_active": <is_active> 
      }
      """
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method post
    Then status 201
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '##string'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#[] string'
    And match response.error_info == '##string'

    Examples:
      | read('country_post.csv') |
