// ********RoostGPT********
/*
Test generated by RoostGPT for test restassured-apitest-01 using AI Type Open AI and AI Model gpt-4o

Test generated for /appointment_post for http method type POST in rest-assured framework

RoostTestHash=d511932aa7

[
  {
    "ScenarioID": "1",
    "TestName": "testValidAppointmentCreation",
    "Description": "Test creating an appointment with valid data",
    "Execution": {
      "Arrange": "Prepare a valid JSON body with all required fields filled correctly",
      "Act": "Send POST request to /appointment with the valid JSON body",
      "Assert": "Check for 201 status and response body contains the appointment details"
    },
    "Validation": "Ensures API successfully creates an appointment with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingAddressId",
    "Description": "Test creating an appointment with missing address ID",
    "Execution": {
      "Arrange": "Prepare a JSON body with address ID missing",
      "Act": "Send POST request to /appointment with the invalid JSON body",
      "Assert": "Check for 400 status and response body contains error message"
    },
    "Validation": "Ensures API returns an error when address ID is missing"
  },
  {
    "ScenarioID": "3",
    "TestName": "testInvalidAddressIdType",
    "Description": "Test creating an appointment with address ID as a string instead of a number",
    "Execution": {
      "Arrange": "Prepare a JSON body with address ID as a string",
      "Act": "Send POST request to /appointment with the invalid JSON body",
      "Assert": "Check for 400 status and response body contains error message"
    },
    "Validation": "Ensures API returns an error when address ID is of incorrect type"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidPriorityFlagType",
    "Description": "Test creating an appointment with priority flag as a string instead of a boolean",
    "Execution": {
      "Arrange": "Prepare a JSON body with priority flag as a string",
      "Act": "Send POST request to /appointment with the invalid JSON body",
      "Assert": "Check for 400 status and response body contains error message"
    },
    "Validation": "Ensures API returns an error when priority flag is of incorrect type"
  },
  {
    "ScenarioID": "5",
    "TestName": "testMissingAuthToken",
    "Description": "Test creating an appointment without an authentication token",
    "Execution": {
      "Arrange": "Prepare a valid JSON body without including an auth token",
      "Act": "Send POST request to /appointment without auth token",
      "Assert": "Check for 401 status and response body contains unauthorized message"
    },
    "Validation": "Ensures API requires authentication token for creating an appointment"
  },
  {
    "ScenarioID": "6",
    "TestName": "testInvalidOrderType",
    "Description": "Test creating an appointment with an invalid order type",
    "Execution": {
      "Arrange": "Prepare a JSON body with an invalid order type",
      "Act": "Send POST request to /appointment with the invalid JSON body",
      "Assert": "Check for 400 status and response body contains error message"
    },
    "Validation": "Ensures API returns an error when order type is invalid"
  },
  {
    "ScenarioID": "7",
    "TestName": "testEmptyProductArray",
    "Description": "Test creating an appointment with an empty product array",
    "Execution": {
      "Arrange": "Prepare a JSON body with an empty product array",
      "Act": "Send POST request to /appointment with the invalid JSON body",
      "Assert": "Check for 400 status and response body contains error message"
    },
    "Validation": "Ensures API returns an error when product array is empty"
  },
  {
    "ScenarioID": "8",
    "TestName": "testTooManyRequests",
    "Description": "Test rate limiting by sending too many requests in a short period",
    "Execution": {
      "Arrange": "Prepare a valid JSON body",
      "Act": "Send multiple POST requests to /appointment in quick succession",
      "Assert": "Check for 429 status and response body contains too many requests message"
    },
    "Validation": "Ensures API enforces rate limiting"
  },
  {
    "ScenarioID": "9",
    "TestName": "testServiceUnavailable",
    "Description": "Test server response when service is unavailable",
    "Execution": {
      "Arrange": "Simulate service downtime",
      "Act": "Send POST request to /appointment during downtime",
      "Assert": "Check for 503 status and response body contains service unavailable message"
    },
    "Validation": "Ensures API handles service unavailability gracefully"
  },
  {
    "ScenarioID": "10",
    "TestName": "testInternalServerError",
    "Description": "Test server response to an unexpected internal error",
    "Execution": {
      "Arrange": "Simulate a server error condition",
      "Act": "Send POST request to /appointment",
      "Assert": "Check for 500 status and response body contains internal server error message"
    },
    "Validation": "Ensures API returns appropriate error message for internal server errors"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class AppointmentPostTest {

	List<JSONObject> testCases = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		testCases = dataloader.loadJson("src/test/java/com/bootexample4/RoostTest/appointmentPostTest.JSON");
	}

	@Test
    public void AppointmentPost_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = https://127.0.0.1:4010;

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/appointment";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "api/appointment-v2.json";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("post".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "post");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: AppointmentPost_Test\n", testNumber++);
            System.out.println("Request: POST " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }

}
