# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /appointmentConfirmation_post for http method type POST 
# RoostTestHash=d3e6c8c6f7
# 
# 

# ********RoostGPT********
Feature: Appointment Confirmation API test suite

  Background:
    * def baseURL = karate.properties['APPOINTMENT_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Validate Appointment Confirmation API - Success Response (200)
    Given path '/appointmentConfirmation'
    And request
      """
        {
          "appointment": {
            "confirmation": <confirmation>,
            "id": <id>
          },
          "customer": {
            "subscriberId": <subscriberId>
          }
        }
      """
    When method POST
    Then status 200
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | read('appointmentConfirmation_post.csv') |

  Scenario Outline: Validate Appointment Confirmation API - Error Responses
    Given path '/appointmentConfirmation'
    And request
      """
        {
          "appointment": {
            "confirmation": <confirmation>,
            "id": <id>
          },
          "customer": {
            "subscriberId": <subscriberId>
          }
        }
      """
    When method POST
    Then assert responseStatus == <status>
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | confirmation | id          | subscriberId | status |
      | true         | ''          | ['VTAL001']  |    400 |
      | true         | 'SA-562403' | []           |    400 |

  Scenario: Validate Unauthorized Response (401)
    Given path '/appointmentConfirmation'
    And request
      """
        {
          "appointment": {
            "confirmation": true,
            "id": "SA-562403"
          },
          "customer": {
            "subscriberId": "VTAL001"
          }
        }
      """
    When method POST
    Then assert responseStatus == 401
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate Forbidden Response (403)
    Given path '/appointmentConfirmation'
    And request
      """
        {
          "appointment": {
            "confirmation": true,
            "id": "SA-562403"
          },
          "customer": {
            "subscriberId": "VTAL001"
          }
        }
      """
    When method POST
    Then assert responseStatus == 403
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate Internal Server Error Response (500)
    Given path '/appointmentConfirmation'
    And request
      """
        {
          "appointment": {
            "confirmation": true,
            "id": "SA-562403"
          },
          "customer": {
            "subscriberId": "VTAL001"
          }
        }
      """
    When method POST
    Then assert responseStatus == 500
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
