# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=36bc161fb6
# 
# 

# ********RoostGPT********
Feature: Verify Employee API functionalities

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'
    * header Authorization = '#{processEnvironment.AUTH_TOKEN}'

  Scenario Outline: Fetch an employee by ID
    Given path 'employees', <id>
    And method GET
    When status == 200
    Then match response == '#object'
    And match response.id == '#uuid'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'
    And match response.email == '#regex ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}'
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | id                                     |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0851' |

  Scenario: Fetch an employee by invalid ID
    Given path 'employees', 'invalid-id'
    And method GET
    When assert responseStatus != 200
    Then match response == null
