# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employee Search API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate employee search API with query parameter
    Given path 'employees'
    And param searchString = '<searchString>'
    When method GET
    Then status 200
    And match response == #[]
    And match each response[*].id == '#uuid'
    And match each response[*].name == '#string'
    And match each response[*].email == '#string'
    And match each response[*].jobTitle == '#string'

    Examples:
      | read('employees_get.csv') |

  Scenario: Validate employee search API without query parameter
    Given path 'employees'
    When method GET
    Then status 200
    And match response == #[]
    And match each response[*].id == '#uuid'
    And match each response[*].name == '#string'
    And match each response[*].email == '#string'
    And match each response[*].jobTitle == '#string'

  Scenario: Validate employee search API with bad input
    Given path 'employees'
    And param searchString = """123456"""
    When method GET
    Then status 400
