# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=b517afeac4
# 
# 

# ********RoostGPT********
Feature: Test Employee Management API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'
    * header Authorization = 'Bearer {{$processEnvironment.AUTH_TOKEN}}'

  Scenario Outline: Add a new employee with valid input payload
    Given path 'employees'
    And request
      """
      {
        "email": "<email>",
        "jobTitle": "<jobTitle>",
        "name": "<name>"
      }
      """
    When method POST
    Then status 201
    And match response == null
    And match responseHeaders.location == '#string'

    Examples:
      | read('employees_post.csv') |

  Scenario Outline: Add an employee with missing required fields
    Given path 'employees'
    And request
      """
      {
        "email": "<email>",
        "jobTitle": "<jobTitle>"
      }
      """
    When method POST
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | email                   | jobTitle         |
      | 'missing.name@acme.com' | 'System Analyst' |

  Scenario Outline: Add an employee with duplicate entry
    Given path 'employees'
    And request
      """
      {
        "email": "<email>",
        "jobTitle": "<jobTitle>",
        "name": "<name>"
      }
      """
    When method POST
    Then status 409
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | email                      | jobTitle         | name         |
      | 'john.smith@acme-corp.com' | 'System Analyst' | 'John Smith' |
